import { access, mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import type { CreatePassRequest } from "../types/pass";
import { generatedPassesDir } from "../config/paths";
import type { PassJson } from "./passJson.service";

export const PKPASS_MIME_TYPE = "application/vnd.apple.pkpass";

const PASS_ID_PATTERN = /^[a-zA-Z0-9_-]+$/;

function isSafePassId(passId: string) {
  return PASS_ID_PATTERN.test(passId);
}

function getPassFilePath(passId: string) {
  if (!isSafePassId(passId)) {
    return null;
  }

  return path.join(generatedPassesDir, `${passId}.pkpass`);
}

function getDebugPassJsonFilePath(passId: string) {
  if (!isSafePassId(passId)) {
    return null;
  }

  return path.join(generatedPassesDir, `debug-${passId}.json`);
}

export async function createPlaceholderPassFile(
  passId: string,
  request: CreatePassRequest,
) {
  const filePath = getPassFilePath(passId);

  if (!filePath) {
    throw new Error("Invalid pass ID.");
  }

  await mkdir(generatedPassesDir, { recursive: true });
  await writeFile(
    filePath,
    JSON.stringify(
      {
        message: "Placeholder .pkpass generated by the Phase 6 API skeleton.",
        passId,
        request,
      },
      null,
      2,
    ),
  );

  return filePath;
}

export async function saveDebugPassJsonFile(passId: string, passJson: PassJson) {
  const filePath = getDebugPassJsonFilePath(passId);

  if (!filePath) {
    throw new Error("Invalid pass ID.");
  }

  await mkdir(generatedPassesDir, { recursive: true });
  await writeFile(filePath, JSON.stringify(passJson, null, 2));

  return filePath;
}

export async function findPassFile(passId: string) {
  const filePath = getPassFilePath(passId);

  if (!filePath) {
    return null;
  }

  try {
    await access(filePath);
    return filePath;
  } catch {
    return null;
  }
}
